# Generated by Django 6.0.6 on 2026-07-03 10:06

import croploraApp.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50)),
                (
                    "role_code",
                    models.CharField(
                        help_text="e.g. SUPER_ADMIN, NORMAL_USER",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("role_description", models.TextField(blank=True, null=True)),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=True,
                        help_text="System roles cannot be deleted or modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Role",
                "verbose_name_plural": "Platform Roles",
                "db_table": "platform_roles",
                "ordering": ["role_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from email if not provided",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user_code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated e.g. USR1A2B3C4D",
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language_code", models.CharField(default="en", max_length=10)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "org_code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated e.g. ORG00123",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from name",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=croploraApp.models.org_logo_upload_location,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("onboarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="croploraApp.organization",
            ),
        ),
        migrations.CreateModel(
            name="OrgRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50)),
                (
                    "role_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique role code per org",
                        max_length=20,
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("OWNER", "Organization Owner"),
                            ("ADMIN", "Admin"),
                            ("WORKER", "Worker"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="OWNER / ADMIN / WORKER / CUSTOM",
                        max_length=20,
                    ),
                ),
                ("role_description", models.TextField(blank=True, null=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default roles cannot be edited or deleted",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_roles",
                        to="croploraApp.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Org Role",
                "verbose_name_plural": "Org Roles",
                "db_table": "org_roles",
                "ordering": ["organization", "role_name"],
                "unique_together": {
                    ("organization", "role_code"),
                    ("organization", "role_name"),
                },
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Sent in the invite link",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="croploraApp.organization",
                    ),
                ),
                (
                    "org_role",
                    models.ForeignKey(
                        help_text="Role that will be assigned to the user on accepting",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="croploraApp.orgrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "db_table": "invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="org_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="croploraApp.orgrole",
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="platform_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="croploraApp.platformrole",
            ),
        ),
        migrations.CreateModel(
            name="OrgUser",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "org_user_code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated e.g. EMP1A2B3C4",
                        max_length=25,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z\\s\\-\\.\\']+$",
                                "Only letters, spaces, hyphens, dots, and apostrophes are allowed.",
                            )
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z\\s\\-\\.\\']+$",
                                "Only letters, spaces, hyphens, dots, and apostrophes are allowed.",
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-(). ]+$",
                                "Only numeric characters and phone symbols are allowed.",
                            )
                        ],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=croploraApp.models.org_user_profile_image_upload_location,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_users",
                        to="croploraApp.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Org User",
                "verbose_name_plural": "Org Users",
                "db_table": "org_users",
                "ordering": ["organization", "first_name", "last_name"],
                "unique_together": {("organization", "org_user_code")},
            },
        ),
    ]
