# Generated by Django 6.0.6 on 2026-07-06 09:47

from django.db import migrations


def create_platform_roles(apps, schema_editor):
    PlatformRole = apps.get_model("croploraApp", "PlatformRole")
    PlatformRole.objects.get_or_create(
        role_code="SUPER_ADMIN", defaults={"role_name": "Super Admin"}
    )
    PlatformRole.objects.get_or_create(
        role_code="NORMAL_USER", defaults={"role_name": "Normal User"}
    )


def reverse_func(apps, schema_editor):
    PlatformRole = apps.get_model("croploraApp", "PlatformRole")
    PlatformRole.objects.filter(role_code__in=["SUPER_ADMIN", "NORMAL_USER"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("croploraApp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_platform_roles, reverse_func),
    ]
