# Generated by Django 6.0.6 on 2026-07-17 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croploraApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgrole",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="orgrole",
            name="role_type",
        ),
        migrations.AddField(
            model_name="orgrole",
            name="is_system_role",
            field=models.BooleanField(
                default=True, help_text="System roles cannot be deleted or modified"
            ),
        ),
        migrations.AlterField(
            model_name="orgrole",
            name="role_code",
            field=models.CharField(
                choices=[
                    ("OWNER", "Organization Owner"),
                    ("ADMIN", "Admin"),
                    ("WORKER", "Worker"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orguser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9+\\-(). ]+$",
                        "Only numeric characters and phone symbols are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="platformrole",
            name="role_code",
            field=models.CharField(
                choices=[
                    ("NORMAL_USER", "Normal User"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
